### ISSUE TITLE
ZPMs disappear out of hubs

### ISSUE THREAD

**Issue by TheGuppy525** [MayusYT/ZPM-Mod#11]
both large and small ZPM hubs ZPMs disappear out of the hubs at random times

**Comment by realmayus** [comment]
What hubs do you mean? The controllers? 
Please give me a log.

**Comment by TheGuppy525** [comment]
its the controllers

**Comment by realmayus** [comment]
I need a log in order to help you further

**Comment by realmayus** [comment]
Closing this issue due to no response. If you still want to help me, feel free to reopen the issue. I'd appreciate it because that helps me to improve the mod.

**Comment by craft90** [comment]
Not the one whom opened this issue but I encountered the same issue. It appears to be a chunk unloading issue.  When the chunk unloads, the ZPM goes by bye.

**Comment by realmayus** [comment]
Hi, thanks again for your comment. I looked through the code and saw that I don't even save the items in NBT *facepalm*
Will fix this ASAP.
