### ISSUE TITLE
enderIO pulls out full zpms even if they are blacklisted

### ISSUE THREAD

**Issue by realmayus** [MayusYT/ZPM-Mod#12]
enderIO pulls out full zpms even if they are blacklisted

**Comment by BDevGW** [comment]
Solution: Use advanced itemfilter with advanced NBT filter.

**Comment by realmayus** [comment]
Thanks for the tip!

**Comment by BDevGW** [comment]
You already wrote this on another site, just added it if someone else with this problem finds this unanswered issue so he has the solution :)
