### ISSUE TITLE
Game just crash when trying to obtain small or large ZPM hub, way don't matter.

### ISSUE THREAD

**Issue by KamaroTheN7** [MayusYT/ZPM-Mod#13]
**I'm using Minecraft Forge, version:forge-1.12.2-14.23.5.2847**

**Steps to reproduce**
1. just grab small or large ZPM hub
2. try to insert it in yours inventory
3. game crash

**Server/Client Log**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.262.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 4/25/20 12:19 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BC Fuels For IC2 (bcfuelsforic2)
Caused by: java.lang.NullPointerException
	at com.xxTFxx.bcfuelsforic2.BCFuelsForIC2.init(BCFuelsForIC2.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1296308432 bytes (1236 MB) / 4563402752 bytes (4352 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                          | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                         | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LCHI  | mcp                               | 9.42                     | minecraft.jar                                   | None                                     |
	| LCHI  | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LCHI  | forge                             | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LCHI  | micdoodlecore                     |                          | minecraft.jar                                   | None                                     |
	| LCHI  | openmodscore                      | 0.12.2                   | minecraft.jar                                   | None                                     |
	| LCHI  | opencomputers|core                | 1.7.5.192                | minecraft.jar                                   | None                                     |
	| LCHI  | actuallyadditions                 | 1.12.2-r151              | ActuallyAdditions-1.12.2-r151-2.jar             | None                                     |
	| LCHI  | applecore                         | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                    | None                                     |
	| LCHI  | jei                               | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                       | None                                     |
	| LCHI  | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| LCHI  | aroma1997core                     | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHI  | aroma1997sdimension               | 2.0.0.2                  | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHE  | bcfuelsforic2                     | 1.0                      | BCFuelsForIC2.jar                               | None                                     |
	| LCH   | buildcraftlib                     | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
	| LCH   | buildcraftcore                    | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
	| LCH   | buildcraftbuilders                | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
	| LCH   | buildcrafttransport               | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
	| LCH   | buildcraftsilicon                 | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
	| LCH   | buildcraftenergy                  | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
	| LCH   | forestry                          | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                   | None                                     |
	| LCH   | buildcraftcompat                  | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
	| LCH   | buildcraftfactory                 | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
	| LCH   | buildcraftrobotics                | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
	| LCH   | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux                      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
	| LCH   | cofhcore                          | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar           | None                                     |
	| LCH   | cofhworld                         | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar          | None                                     |
	| LCH   | asielib                           | 1.0.0                    | Computronics-1.12.2-1.6.6.jar                   | None                                     |
	| LCH   | endercore                         | 1.12.2-0.5.73            | EnderCore-1.12.2-0.5.73.jar                     | None                                     |
	| LCH   | thermalfoundation                 | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar  | None                                     |
	| LCH   | thermalexpansion                  | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar   | None                                     |
	| LCH   | enderio                           | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LCH   | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCH   | opencomputers                     | 1.7.5.192                | OpenComputers-MC1.12.2-1.7.5.192.jar            | None                                     |
	| LCH   | railcraft                         | 12.0.0                   | railcraft-12.0.0.jar                            | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCH   | computronics                      | 1.6.6                    | Computronics-1.12.2-1.6.6.jar                   | None                                     |
	| LCH   | enderiointegrationtic             | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LCH   | enderiobase                       | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LCH   | enderioconduits                   | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LCH   | enderioconduitsrefinedstorage     | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LCH   | enderiointegrationforestry        | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LCH   | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCH   | twilightforest                    | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar   | None                                     |
	| LCH   | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
	| LCH   | enderiointegrationticlate         | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LCH   | enderiomachines                   | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LCH   | enderiopowertools                 | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LCH   | enderioendergy                    | 5.1.55                   | EnderIO-endergy-1.12.2-5.1.55.jar               | None                                     |
	| LCH   | enderiozoo                        | 5.1.55                   | EnderIO-zoo-1.12.2-5.1.55.jar                   | None                                     |
	| LCH   | enderstorage                      | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | energyconverters                  | 1.3.6.24                 | energyconverters_1.12.2-1.3.6.24.jar            | None                                     |
	| LCH   | galacticraftcore                  | 4.0.2.262                | GalacticraftCore-1.12.2-4.0.2.262.jar           | None                                     |
	| LCH   | galacticraftplanets               | 4.0.2.262                | Galacticraft-Planets-1.12.2-4.0.2.262.jar       | None                                     |
	| LCH   | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
	| LCH   | journeymap                        | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                     | None                                     |
	| LCH   | malisiscore                       | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                    | None                                     |
	| LCH   | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                   | None                                     |
	| LCH   | neat                              | 1.4-17                   | Neat+1.4-17.jar                                 | None                                     |
	| LCH   | nei                               | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | openmods                          | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | openblocks                        | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | harvestcraft                      | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zg.jar                 | None                                     |
	| LCH   | sgcraft                           | 2.0.3                    | SGCraft-2.0.3.jar                               | None                                     |
	| LCH   | stairway                          | v09                      | Stairway_1.12.2_v09.jar                         | None                                     |
	| LCH   | thermalcultivation                | 0.3.6                    | ThermalCultivation-1.12.2-0.3.6.1-universal.jar | None                                     |
	| LCH   | thermaldynamics                   | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar    | None                                     |
	| LCH   | thermalinnovation                 | 0.3.6                    | ThermalInnovation-1.12.2-0.3.6.1-universal.jar  | None                                     |
	| LCH   | wawla                             | 2.6.275                  | Wawla-1.12.2-2.6.275.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | hungeroverhaul                    | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar      | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.262.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Misc**
that what minecraft luncher display:
The game crashed whilst ticking player
Error: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block zpmmod:controller_large, it is not an allowed value

**Photos/Videos**

**Comment by bl4ckscor3** [comment]
The crash report you provided is not the correct report, as the mod list does not contain ZPM-Mod.

**Comment by KamaroTheN7** [comment]
[crash-2020-04-25_00.31.57-server.txt](https://github.com/realmayus/ZPM-Mod/files/4533211/crash-2020-04-25_00.31.57-server.txt)

Sorry, my mistake

**Comment by realmayus** [comment]
thanks for the report - i'll look into this. Seems like railcraft is involved in the crash again. Oh well.

**Comment by KamaroTheN7** [comment]
> 
> 
> thanks for the report - i'll look into this. Seems like railcraft is involved in the crash again. Oh well.

Railcraft?! and agin?! lol, Its first time to me that this mod is making conflict, thx for making and supporting this mod. Stargate mods without ZPM feels incomplete.

**Comment by realmayus** [comment]
Yeah, I've had some issues with railcraft in my other mod. But I'll have to determine the crash reason first before making any assumptions lol
