### ISSUE TITLE
ZPM hub doesnt work for a server.

### ISSUE THREAD

**Issue by AngelShadow9451** [MayusYT/ZPM-Mod#14]
**I'm using Minecraft Forge, version: 14.23.5.2855

**Steps to reproduce**
1. Load this mod up on a server and connect.
2. Attempt to place either hub down and access
3. Attempt to break either hub, in creative or survival. 

**Server/Client Log**

**Misc**
It becomes indestructible in a server environment, and the GUI is not accessible in any gamemode. I thought at first a corrupt mod but reinstalled and continued to happen. A certain error spammed in the Console, I do not remember but I can reproduce to get the error if needed.

**Photos/Videos**

**Comment by realmayus** [comment]
Hi, thanks for the bug report. Can you post the console log? Otherwise it's really hard to pin point the error.

**Comment by AngelShadow9451** [comment]
[2021-06-15-4.log.gz](https://github.com/realmayus/ZPM-Mod/files/6653645/2021-06-15-4.log.gz)
[crash-2021-06-15_02.19.44-server.txt](https://github.com/realmayus/ZPM-Mod/files/6653646/crash-2021-06-15_02.19.44-server.txt)

**Comment by AngelShadow9451** [comment]
I hope that works? I loaded into the server, changed my gamemode to creative and grabed the items that I am refering to. I think placed them both down, attempted to open their gui's and then placed a power cable right next to one of them.
I ofc had to remove the mod and reload it up without to prevent that from happening again.

**Comment by AngelShadow9451** [comment]
I have FTBUtilities with claims in the area if that could possibly affect it, or I have the AUNIS mod.

**Comment by realmayus** [comment]
Thanks for providing the log. I'm currently working to fix the issue.

**Comment by realmayus** [comment]
@AngelShadow9451 I just published an update resolving this issue. I hope that it helps you! Thanks again for submitting the report!

Here's the download link (now v. 1.2.3): https://www.curseforge.com/minecraft/mc-mods/zpm-mod/files/3360205

**Comment by AngelShadow9451** [comment]
Thank you very much.
